### ISSUE TITLE
error when installing with composer

### ISSUE THREAD

**Issue by danielzzz** [burzum/cakephp-bz-utils#6]
Hi, I'm trying to install it with

composer require burzum/cakephp-bz-utils:dev-master

but I get 
[RuntimeException]  
  Unable to get primary namespace for package burzum/cakephp-bz-utils.  
  Ensure you have added proper 'autoload' section to your plugin's config as  
  stated in README on https://github.com/cakephp/plugin-installer

**Comment by burzum** [comment]
I'll check this next Tuesday, right now I'm not at home nor work - vacations. :)

**Comment by burzum** [comment]
Are you using CakePHP 2.x or 3.x? This plugin is for 2.x.

**Comment by danielzzz** [comment]
ahh, this could be the problem. I was using it with 3.x. Not sure if this make the issue invalid... thanks anyway.

**Comment by burzum** [comment]
What part of the plugin do you want to use?

**Comment by danielzzz** [comment]
I wanted to use JwtTokenAuthenticate part, but at the end I found another plugin compatible with 3.x

thanks, dan

**Comment by burzum** [comment]
Guess it's admads. :)

**Comment by danielzzz** [comment]
I don't remember now, but I think it was his, indeed. thanks!
